# -*- coding: utf-8 -*-
"""text_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbPygbPDzpPqDmGn5uA8y-Pwbkh0Y7OC
"""

pip install requests beautifulsoup4 lxml pandas nltk openpyxl newspaper3k readability-lxml

import pandas as pd
from newspaper import Article
import nltk

try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

def fetch_article(url):
    try:
        article = Article(url)
        article.download()
        article.parse()
        article.nlp()
        return article.title, article.text
    except Exception as e:
        print(f"Error fetching article from {url}: {e}")
        return "", ""

df_in = pd.read_excel('Input.xlsx')  # assumes columns: URL_ID, URL (adjust names)
for idx, row in df_in.iterrows():
    url_id = str(row['URL_ID'])
    url = row['URL']
    title, text = fetch_article(url)
    with open(f'{url_id}.txt', 'w', encoding='utf-8') as f:
        f.write(title + '\n\n' + text)

import requests
from bs4 import BeautifulSoup
from newspaper import Article
from readability import Document

def fetch_article(url, timeout=10):
    # Try newspaper3k first
    try:
        art = Article(url)
        art.download()
        art.parse()
        title = art.title or ''
        text = art.text or ''
        if len(text.split()) > 30:
            return title.strip(), text.strip()
    except Exception:
        pass

    # Fallback: requests + readability
    try:
        resp = requests.get(url, timeout=timeout, headers={'User-Agent':'Mozilla/5.0'})
        resp.raise_for_status()
        doc = Document(resp.text)
        title = doc.short_title()
        cleaned_html = doc.summary()   # returns main content HTML
        soup = BeautifulSoup(cleaned_html, 'lxml')
        text = soup.get_text(separator='\n')
        if text:
            return title.strip(), text.strip()
    except Exception:
        pass

    # Last fallback: naive BeautifulSoup extraction
    try:
        resp = requests.get(url, timeout=timeout, headers={'User-Agent':'Mozilla/5.0'})
        soup = BeautifulSoup(resp.text, 'lxml')
        # Try common article tags
        article = soup.find('article')
        if article:
            title = (article.find('h1') or soup.find('h1')).get_text(strip=True)
            text = ' '.join(p.get_text() for p in article.find_all('p'))
            return title.strip(), text.strip()
        # generic fallbacks
        title = (soup.find('h1') or soup.title).get_text(strip=True)
        paragraphs = soup.find_all('p')
        text = ' '.join(p.get_text() for p in paragraphs)
        return title.strip(), text.strip()
    except Exception:
        return '', ''

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
# If you have a custom stopwords folder, load it and update stop_words:
# custom = open('StopWords/StopWords_Auditor.txt').read().splitlines()
# stop_words.update([w.strip().lower() for w in custom])

def load_wordlist(path):
    return set(w.strip().lower() for w in open(path, encoding='latin-1') if w.strip())

positive = load_wordlist('/content/positive-words.txt')
negative = load_wordlist('/content/negative-words.txt')

# remove stopwords if required
positive = {w for w in positive if w not in stop_words}
negative = {w for w in negative if w not in stop_words}

import re

def sentiment_scores(tokens):
    pos = sum(1 for t in tokens if t in positive)
    neg = sum(1 for t in tokens if t in negative)
    polarity = (pos - neg) / ((pos + neg) + 1e-6)
    subj = (pos + neg) / (len(tokens) + 1e-6)
    return pos, neg, polarity, subj

import re

vowels = "aeiouy"

def count_syllables(word):
    word = word.lower().strip()
    if len(word) <= 3:
        return 1
    # remove trailing 'es' or 'ed' sometimes not syllabic
    word = re.sub(r'[^a-z]', '', word)
    word = re.sub(r'(es|ed)$', '', word)
    # count vowel groups
    groups = re.findall(r'[aeiouy]+', word)
    syllables = len(groups)
    # ensure at least 1
    return syllables if syllables > 0 else 1

def is_complex(word):
    return count_syllables(word) > 2

def readability_metrics(words, sentences):
    word_count = len(words)
    sentence_count = max(len(sentences), 1)
    avg_sentence_length = word_count / sentence_count
    complex_count = sum(1 for w in words if is_complex(w))
    pct_complex = complex_count / (word_count + 1e-6)
    fog_index = 0.4 * (avg_sentence_length + (pct_complex * 100))  # careful: doc's % maybe decimal or percent
    # NOTE: the original doc says Percentage of Complex words = number complex / number words
    # Fog formula in doc: 0.4*(Avg sentence length + Percentage of Complex words)
    # If Percentage is decimal (0.12) then Fog small; many sources use percentage (12), so both appear.
    # Use doc literal: if document intends decimal, remove *100 above.
    return avg_sentence_length, pct_complex, fog_index, complex_count, word_count

import string

def clean_words(text):
    tokens = word_tokenize(text)
    words = []
    for t in tokens:
        w = t.lower()
        w = w.strip(string.punctuation)
        if w == '' or w in stop_words:
            continue
        words.append(w)
    return words

def avg_syllables_per_word(words):
    total_syll = sum(count_syllables(w) for w in words)
    return total_syll / (len(words) + 1e-6)

def count_personal_pronouns(text):
    # convert to tokenized words with original case for 'US' check
    # pattern will find I, we, my, ours, us (word boundaries, case-insensitive)
    pattern = re.compile(r'\b(I|we|my|ours|us)\b', re.IGNORECASE)
    matches = pattern.findall(text)
    # filter out 'US' as country: if the matched token upper() == 'US' and context suggests country, skip
    filtered = []
    for m in matches:
        if m.lower() == 'us':
            # check context: if 'the us' or 'us.' often country; as safer approach, exclude 'US' only when uppercase in original
            # We'll check the original text with word boundaries for uppercase 'US'
            # But here we don't have original matched case; a robust option:
            # Count 'us' when match is lowercase in original substring; to get original substring use re.finditer
            pass
    # better approach: use finditer to inspect original matched substring
def count_personal_pronouns(text):
    pattern = re.compile(r'\b(I|we|my|ours|us)\b', re.IGNORECASE)
    count = 0
    for m in pattern.finditer(text):
        token = m.group(0)
        # skip if token is exactly 'US' in uppercase (likely country)
        if token == 'US':
            continue
        count += 1
    return count

def avg_word_length(words):
    total_chars = sum(len(w) for w in words)
    return total_chars / (len(words) + 1e-6)

def analyze_article(title, text):
    sentences = sent_tokenize(text)
    words_all = [w for w in word_tokenize(text)]
    cleaned_words = clean_words(text)  # stopwords removed, punctuation removed
    pos, neg, polarity, subj = sentiment_scores([w.lower() for w in cleaned_words])
    avg_sent_len, pct_complex, fog_index, complex_count, word_count = readability_metrics(cleaned_words, sentences)
    avg_words_per_sentence = avg_sent_len
    syll_per_word = avg_syllables_per_word(cleaned_words)
    personal_pron = count_personal_pronouns(text)
    avg_wlen = avg_word_length(cleaned_words)
    # return dict in required order
    return {
        'POSITIVE SCORE': pos,
        'NEGATIVE SCORE': neg,
        'POLARITY SCORE': polarity,
        'SUBJECTIVITY SCORE': subj,
        'AVG SENTENCE LENGTH': avg_sent_len,
        'PERCENTAGE OF COMPLEX WORDS': pct_complex,
        'FOG INDEX': fog_index,
        'AVG NUMBER OF WORDS PER SENTENCE': avg_words_per_sentence,
        'COMPLEX WORD COUNT': complex_count,
        'WORD COUNT': word_count,
        'SYLLABLE PER WORD': syll_per_word,
        'PERSONAL PRONOUNS': personal_pron,
        'AVG WORD LENGTH': avg_wlen
    }

results = []
for idx, row in df_in.iterrows():
    url_id = row['URL_ID']
    title, text = fetch_article(row['URL'])
    # optionally save article text file as required
    with open(f'{url_id}.txt', 'w', encoding='utf-8') as f:
        f.write(title + '\n\n' + text)
    metrics = analyze_article(title, text)
    # Prepare output row: include input columns first
    out_row = row.to_dict()
    out_row.update(metrics)
    results.append(out_row)

df_out = pd.DataFrame(results)
# reorder columns: all original input columns followed by required output variables in exact order:
output_cols = list(df_in.columns) + [
    'POSITIVE SCORE','NEGATIVE SCORE','POLARITY SCORE','SUBJECTIVITY SCORE',
    'AVG SENTENCE LENGTH','PERCENTAGE OF COMPLEX WORDS','FOG INDEX',
    'AVG NUMBER OF WORDS PER SENTENCE','COMPLEX WORD COUNT','WORD COUNT',
    'SYLLABLE PER WORD','PERSONAL PRONOUNS','AVG WORD LENGTH'
]
df_out = df_out[output_cols]
df_out.to_excel('Output_Data_Structure.xlsx', index=False)